/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as ChatManagerRouteImport } from './routes/chat-manager'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatManagerRoute = ChatManagerRouteImport.update({
  id: '/chat-manager',
  path: '/chat-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calls': typeof CallsRoute
  '/channels': typeof ChannelsRoute
  '/chat-manager': typeof ChatManagerRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calls': typeof CallsRoute
  '/channels': typeof ChannelsRoute
  '/chat-manager': typeof ChatManagerRoute
  '/teams': typeof TeamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calls': typeof CallsRoute
  '/channels': typeof ChannelsRoute
  '/chat-manager': typeof ChatManagerRoute
  '/teams': typeof TeamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calls'
    | '/channels'
    | '/chat-manager'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/calls' | '/channels' | '/chat-manager' | '/teams'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calls'
    | '/channels'
    | '/chat-manager'
    | '/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CallsRoute: typeof CallsRoute
  ChannelsRoute: typeof ChannelsRoute
  ChatManagerRoute: typeof ChatManagerRoute
  TeamsRoute: typeof TeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-manager': {
      id: '/chat-manager'
      path: '/chat-manager'
      fullPath: '/chat-manager'
      preLoaderRoute: typeof ChatManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CallsRoute: CallsRoute,
  ChannelsRoute: ChannelsRoute,
  ChatManagerRoute: ChatManagerRoute,
  TeamsRoute: TeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
